### PR TITLE
Ruby codegen

### PR DESCRIPTION
**Pull request by BaptisteGelez**
This is an alternative for #34 that generates the languages list with the Ruby helper in `misc`. It just needs to be run after a language is added to the list, as before. It removes the needs for almost all build dependencies, since all CSV and JSON parsing are now done in Ruby.

### CODE REVIEW

**Comment by greyblake** [comment]
@BaptisteGelez Thanks for the PR. I'll take a look this week

**Comment by greyblake** [comment]
@BaptisteGelez I am really sorry. Still didn't not have time to dedicate to your PR.
Just to let you know, that I keep it in mind.

**Comment by greyblake** [comment]
@BaptisteGelez Thanks for the PR!
I'll merge it.
The tests fail because there meanwhile a new language was added (Afrikaans), but it is easy to fix by regenerating `lang.rs`.

**Comment by BaptisteGelez** [comment]
Thank you for merging this! :blush:

**Comment by BaptisteGelez** [comment]
Thank you for merging this! :blush:

**Comment by greyblake** [comment]
@BaptisteGelez thank you :)

**Pull request merged**
