### PR TITLE
Add missing commas

### PR DESCRIPTION
**Pull request by kud1ing**
Github complains

### CODE REVIEW

**Comment by greyblake** [comment]
@kud1ing  Thanks =)

**Comment by kud1ing** [comment]
Oh, and maybe it should be "supported_languages.csv" instead of "supported_laguages.csv".

**Comment by greyblake** [comment]
@kud1ing You're right. That's a typo, thanks for pointing to that!

**Comment by greyblake** [comment]
I just fixed that :)

**Pull request merged**
