### PR TITLE
Add support for Latin

### PR DESCRIPTION
**Pull request by xrmx**
Example test taken from Cicero:
https://www.thelatinlibrary.com/cicero/sex.rosc.shtml

### CODE REVIEW

**Comment by greyblake** [comment]
Thanks! Will try to review this week (sorry, overloaded with regular work).
Apart from that: where did you get trigram profile from?

**Comment by xrmx** [comment]
I got the trigrams from Franc and generated the rest with the ruby script. Thanks!

**Comment by greyblake** [comment]
@xrmx Thanks for the PR!
Out of curiosity: what a use case do you have for Latin?

**Comment by xrmx** [comment]
@greyblake use case is to recognize latin exercises from italian ones for a digital latin course, not common i guess :)

**Comment by xrmx** [comment]
BTW a release would be appreciated as we are probably going to revive the python bindings :)

**Comment by greyblake** [comment]
@xrmx Sorry, I've missed your message somehow.
I just released 0.7.4.
Thanks again!

**Pull request merged**
